# Generated by Django 4.2.4 on 2023-10-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CSE(Reguler)', 'CSE(R)'), ('AIDS(Reguler)', 'AIDS(R)'), ('CSE(HONORS)', 'CSE(H)'), ('MECH', 'Mech')], max_length=100),
        ),
    ]
