# Generated by Django 4.2.4 on 2023-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_facultycoursemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.FloatField(default='4', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='ltps',
            field=models.CharField(default='1-1-1-1', max_length=10),
        ),
    ]
