# Generated by Django 4.2.4 on 2023-10-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_course_credits_course_ltps'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycoursemapping',
            name='component_type',
            field=models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('P', 'Practical')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='is_main_faculty',
            field=models.BooleanField(default=True),
        ),
    ]
