# Generated by Django 4.2.4 on 2023-11-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_facultycoursemapping_component_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultycoursemapping',
            old_name='component_type',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='facultycoursemapping',
            old_name='is_main_faculty',
            new_name='type',
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='session',
            field=models.IntegerField(default=1),
        ),
    ]
